name: Github Actions Demo
run-name: ${{ github.actor }} is testing github actions
on: [push]

jobs:
  github-actions-explore:
    runs-on: ubuntu-latest
    steps:
      - name: Name of the event
        run: echo " ${{ github.event_name }} is the event."
      - name: runner-os name and version
        run: echo "This Job currently running on ${{ runner.os }}"
      - name: name of the branch and repositry it will run
        run: echo "the name of the repo is ${{ github.repository }}, and the name of your branch is ${{ github.ref }}"
      
      - name: checkout the code
        uses: actions/checkout@v4
        run: echo "the clonned repositry is $ {{ github.repository }}"

      - name: list of files in repositry
        run: |
          ls ${{ github.workspace }}
      - run: echo "the job status is ${{ job.status }}"
